# Dependencies
markdown:         redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Syllabi
tagline:          'Courses taught by P. Kerim Friedman'
description:      'A list of courses taught by <a href="http://kerim.oxus.net">P. Kerim Friedman 傅可恩</a>..'
url:              http://kerim.github.io/
baseurl:          /syllabi

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

author:
  name:           'P. Kerim Friedman'
  url:            https://twitter.com/kerim

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

prose:
  siteurl: 'http://kerim.oxus.net/syllabi'
  media: 'media'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - /_posts
    - atom.xml
    - robots.txt
    - /public
    - 404.html
    - LICENSE.md