# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Syllabi
tagline:          'Courses taught by P. Kerim Friedman'
description:      'A list of courses taught by <a href="http://kerim.oxus.net">P. Kerim Friedman 傅可恩</a>.'
url:              http://kerim.github.io/
baseurl:          /syllabi

author:
  name:           'P. Kerim Friedman'
  url:            https://twitter.com/kerim

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


  